on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16' # or the version you are using

      - uses: actions/configure-pages@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: index.qmd # By default, the current working dir is used i.e `quarto render .`

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "node_modules|.git|.husky"
          path: /home/runner/work/MarkdownSlideCompare/MarkdownSlideCompare
          depth: 4

      # Upload the index.html and revealMD directory
      - uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@v2
